### ISSUE TITLE
Error in the front controller

### ISSUE THREAD

**Issue by Foine** [novius-os/noviusos_form#11]
Hello.
I saw this error in the app when I submit a form. I just do some changes in the rendering event and before the submission. But I just add a mail in the form_submit_email propertie and some options in a select. So it doesn't seems to be related to the following error : 

```
    Warning!

    ErrorException [ Warning ]: Invalid argument supplied for foreach()

    /noviusos_form/classes/controller/front.ctrl.php @ line 474:
    473:    foreach ((array) \Event::trigger_function('noviusos_form::data_validation', array(&$data, $fields, $form), 'array') as $array) {
    474:    foreach ($array as $name => $error) {
    475:    $errors[$name] = $error.(isset($errors[$name]) ? "\n".$errors[$name] : '');
```

Thanks for your attention.

**Comment by felixgilles** [comment]
Thank for this report

If event `noviusos_form::data_validation` returns something, this must be an array. But it can also returned nothing.
This commit 2b5e257dc347de8aae53ca94acdee3153da78712 fixes this issue.
