### ISSUE TITLE
Error when editing a form

### ISSUE THREAD

**Issue by Unibozu** [novius-os/noviusos_form#4]
Hi,

I made a fresh install few hours ago. The Form application seems to be working with some errors.

Every time I try to edit a form I have a "Connection Error". Here is a screenshot of the AJAX query content.
![noviusos-bugform](https://f.cloud.github.com/assets/1690498/259664/3c8860b0-8cc3-11e2-904d-45be598bffcb.PNG)

Note : it seems my form was successfully added. However the first time I tried to add a new form it didn't created it. Some errors about duplicate URL what disappeared.

Cheers

**Comment by felixgilles** [comment]
Hi Clement,  

I found ! 

Today I home working, my PHP version is 5.4 and I've got the same issue.  

It's fixed.

**Comment by Unibozu** [comment]
Sweet! I think mine is 5.3, but I'm glad it is fixed now. Cheers

Gilles FELIX notifications@github.com wrote:

> Hi Clement,  
> 
> I found ! 
> 
> Today I home working, my PHP version is 5.4 and I've got the same
> issue.  
> 
> It's fixed.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/novius-os/noviusos_form/issues/4#issuecomment-15303586

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by felixgilles** [comment]
Clement, can you verify precisely your version ? I like to be sure :smile:

**Comment by Unibozu** [comment]
I checked right now, I'm on 5.4 as well... Actually I'm the first surprised Ubuntu is using the version 5.4 ! :)

``` bash
$ php --version
PHP 5.4.6-1ubuntu1.2 (cli) (built: Mar 11 2013 14:57:54) 
```

**Comment by felixgilles** [comment]
It seems that Ubuntu install PHP 5.4 since 12.10 version
